### ISSUE TITLE
Build shouldn't do weird stuff by default

### ISSUE THREAD

**Issue by ph-hs** [greensopinion/greenbeans#3]
'mvn package' has a contract, that does not include opening Finder, implying something, closing finder, and possibly more.

<img width="545" alt="screen shot 2016-06-03 at 8 36 04 am" src="https://cloud.githubusercontent.com/assets/10211993/15778827/b08ffdd6-2966-11e6-9144-6fa171dc3688.png">

Should have a profile "-P promptUserForInstall", etc

**Comment by greensopinion** [comment]
Agreed, it looks a little unusual.   These windows popping up are a side-effect of building the installer (they're not actually asking you to install anything).  You can see the pom here: https://github.com/greensopinion/greenbeans/blob/master/application/pom.xml

Do you have any suggestions about how to improve this?  Not sure if we can prevent the windows from popping up.

**Comment by greensopinion** [comment]
I've updated the readme to mention this problem, but it would be great if we could do better.  Please reopen this issue or comment if you've got a better idea.

**Comment by ph-hs** [comment]
Readme update is just fine, thanks.  People running builds should look past that, and focus on what's dropped in ./application/target/
