### ISSUE TITLE
Project should come with sample transactions files (CSV, etc)

### ISSUE THREAD

**Issue by ph-hs** [greensopinion/greenbeans#4]
.. and readme should talk about how to find/use them for quick end-user appraisal of the application, and technologies showcased.

**Comment by greensopinion** [comment]
Great idea.  

The app comes with pretty comprehensive help, but it's in-app (not in the readme).  You can see the content here: https://github.com/greensopinion/greenbeans/blob/master/ui/app/views/help/help-index.html

**Comment by ph-hs** [comment]
I came via reddit - https://www.reddit.com/r/programming/comments/4m4fuj/building_a_crossplatform_desktop_application_with/ - I'm wanting to see something running. I went to some effort. Unfortunately I do not have a suitable CSV handy. Thus at a certain page/panel that was prompting me to upload one, I stopped appraising this technology and got on with my day job.

**Comment by greensopinion** [comment]
@ph-hs thanks for the feedback

I'm no longer working on this and have no plans to improve it.  Cheers,

David
